"""
Radiometric calibration for Sentinel-1 GRD amplitude data, following ESA's official
specification (ESA-EOPG-CSCOP-TN-0002, "Radiometric Calibration of S-1 Level-1 Products
Generated by the S-1 IPF"). Planetary Computer hosts the raw GRD amplitude bands (vv/vh)
without applying this calibration, but it also hosts the per-item calibration LUT XML
(schema-calibration-vv/vh) as a plain, keyless-fetchable asset, so we can do the
calibration ourselves rather than use uncalibrated digital numbers.

Formula (distributed targets, GRD):
    sigma0 = DN^2 / A_sigma^2
    sigma0_dB = 10 * log10(sigma0)

where A_sigma is the sigma-nought calibration constant, provided in the LUT as a
sparse grid over (line, pixel) and interpolated bilinearly to arbitrary pixel locations.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from xml.etree import ElementTree as ET

import numpy as np

logger = logging.getLogger(__name__)


@dataclass
class CalibrationLut:
    """Sparse (line, pixel) -> sigmaNought grid parsed from a calibration XML."""

    lines: np.ndarray  # shape (n_vectors,)
    pixels: np.ndarray  # shape (n_vectors, n_pixels) -- pixel index per vector (usually constant)
    sigma_nought: np.ndarray  # shape (n_vectors, n_pixels)

    def value_at(self, line: float, pixel: float) -> float:
        """Bilinear interpolation of the sigma-nought LUT at an arbitrary (line, pixel)."""
        n_vectors = self.lines.shape[0]

        # Find the two bracketing azimuth (line) vectors.
        line_idx = np.searchsorted(self.lines, line)
        i0 = int(np.clip(line_idx - 1, 0, n_vectors - 1))
        i1 = int(np.clip(line_idx, 0, n_vectors - 1))
        if i0 == i1:
            row0 = self._interp_pixel(i0, pixel)
            return row0
        l0, l1 = self.lines[i0], self.lines[i1]
        t = 0.0 if l1 == l0 else (line - l0) / (l1 - l0)
        t = float(np.clip(t, 0.0, 1.0))

        row0 = self._interp_pixel(i0, pixel)
        row1 = self._interp_pixel(i1, pixel)
        return row0 + (row1 - row0) * t

    def _interp_pixel(self, vector_idx: int, pixel: float) -> float:
        px = self.pixels[vector_idx]
        vals = self.sigma_nought[vector_idx]
        # px is sorted ascending by construction (Sentinel-1 LUTs are regular range vectors).
        return float(np.interp(pixel, px, vals))


def parse_calibration_lut(xml_bytes: bytes) -> CalibrationLut:
    root = ET.fromstring(xml_bytes)
    vectors = root.findall("./calibrationVectorList/calibrationVector")
    if not vectors:
        raise ValueError("No calibrationVector entries found in calibration XML.")

    lines: list[int] = []
    pixels: list[list[float]] = []
    sigma: list[list[float]] = []

    for vec in vectors:
        line_el = vec.find("line")
        pixel_el = vec.find("pixel")
        sigma_el = vec.find("sigmaNought")
        if line_el is None or pixel_el is None or sigma_el is None:
            continue
        lines.append(int(line_el.text.strip()))
        pixels.append([float(v) for v in pixel_el.text.split()])
        sigma.append([float(v) for v in sigma_el.text.split()])

    if not lines:
        raise ValueError("Calibration XML contained no usable vectors.")

    order = np.argsort(lines)
    lines_arr = np.array(lines, dtype=np.float64)[order]
    pixels_arr = np.array(pixels, dtype=np.float64)[order]
    sigma_arr = np.array(sigma, dtype=np.float64)[order]

    return CalibrationLut(lines=lines_arr, pixels=pixels_arr, sigma_nought=sigma_arr)


def dn_to_sigma0_db(dn: np.ndarray, calibration_constant: np.ndarray) -> np.ndarray:
    """
    Convert raw GRD amplitude digital numbers to calibrated sigma-nought in dB.
    `calibration_constant` (A_sigma) must already be interpolated to the same shape as `dn`.
    Pixels with non-positive DN or non-positive calibration constant become NaN.
    """
    with np.errstate(divide="ignore", invalid="ignore"):
        sigma0 = (dn.astype(np.float64) ** 2) / (calibration_constant**2)
        sigma0_db = 10.0 * np.log10(sigma0)
    sigma0_db[~np.isfinite(sigma0_db)] = np.nan
    return sigma0_db
